services:
  nginx:
    image: nginx:latest
    restart: unless-stopped

    ports:
      - "127.0.0.1:8081:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro