import type { CardData, CardTag } from "./types";

type CardDefinition = {
  id: string;
  label: string;
  description: string;
  tags: CardTag[];
};

const CARD_DEFINITIONS: CardDefinition[] = [
  { id: "77heavens", label: "77heavens", description: "online jewerly brand.", tags: ["fashion"] },
  { id: "ae2i", label: "AE2I drink ticket", description: "10€ drink ticket from the ae2i, arles's uit student association.", tags: ["food"] },
  { id: "art&nature", label: "Art & Nature", description: "flower shop in eguilles. love the use of papyrus on this one.", tags: ["shop"] },
  { id: "artsenikcreations", label: "Artsenik Creations", description: "creative handcrafted jewerly made from mechanic scraps.", tags: ["fashion","craftsmanship","art"] },
  { id: "blackmoonbotanica", label: "Black Moon Botanica", description: "very cool witchcraft shop in edinburgh.", tags: ["shop"] },
  { id: "brasserieartisanaledesalpilles", label: "Brasserie Artisanale des Alpilles", description: "artisanal brewery in the alpilles.", tags: ["food"] },
  { id: "burgerbelair", label: "Burger Bel Air", description: "great burger joint in bouc-bel-air.", tags: ["food"] },
  { id: "cafearriba", label: "Cafe Arriba", description: "nice cafe in portree, skye. good mac and cheese with leeks.", tags: ["food"] },
  { id: "cpa", label: "CPA", description: "car spare parts seller in châteauneuf les martigues.", tags: ["shop", "miscellaneous"] },
  { id: "chinamarket", label: "China Market", description: "a chinese store in plan-de-campagne, cabriès.", tags: ["shop"] },
  { id: "chrislen", label: "Chrislen", description: "french painter.", tags: ["art"] },
  { id: "diedododa", label: "Diedododa", description: "cute prints, sold at the royal market in edinburgh (or online).", tags: ["art", "shop"] },
  { id: "elamrani", label: "El Amrani", description: "leatherworker in the marrakech souk.", tags: ["craftsmanship", "shop"] },
  { id: "enjoysushi", label: "Enjoy Sushi", description: "sushi restaurant in bouc-bel-air.", tags: ["food"] },
  { id: "epikceramique", label: "Epik Ceramique", description: "custom made pottery, by stephanie verchère.", tags: ["craftsmanship", "art"] },
  { id: "florentin", label: "Florentin", description: "great italian restaurant in plan-de-campagne, very generous portions.", tags: ["food"] },
  { id: "greenbagelcafe", label: "Green Bagel Cafe", description: "great bagel joint in aix-en-provence, serving soup on the side, sadly closed now.", tags: ["food"] },
  { id: "glasseffect", label: "Glass Effect", description: "artisanal glasswork jewerly and sculptures.", tags: ["craftsmanship","art", "fashion"] },
  { id: "grosbao", label: "Gros Bao", description: "sticker from an amazing chinese restaurant chain, in marseille. i love gros bao", tags: ["food"] },
  { id: "highlandcowshop", label: "Highland Cow Shop", description: "a shop containing everything related to hairy highland cows, in edinburgh.", tags: ["shop"] },
  { id: "holo", label: "Holo bus card", description: "hawaiian bus card i was provided during a field trip to hawaii.", tags: ["transport"] },
  { id: "hotelledaum", label: "Hotel de l'Aum", description: "hotel in paris 12.", tags: ["wellness"] },
  { id: "kingpins", label: "Kingpins", description: "reusable arcade pass for any kingpins in the uk.", tags: ["miscellaneous"] },
  { id: "ileagammes", label: "Île à Gammes", description: "thanks card that came with my tie accessory order from ile à gammes, great creator, check our her website.", tags: ["fashion"] },
  { id: "lacageauxfleurs", label: "La Cage aux Fleurs", description: "amazing restaurant in tain-l'hermitage i went to at a business seminar during my internship with miratlas. best white wine of my life.", tags: ["food"] },
  { id: "lacarteblanche", label: "La Carte Blanche", description: "restaurant in marseille.", tags: ["food"] },
  { id: "laciteduchocolat", label: "La Cité du Chocolat", description: "ticket to valrhona's chocolate museum in tain-l'hermitage. i tried 100% cocoa chocolate there, it was awful.", tags: ["food","shop"] },
  { id: "leffetfleur", label: "L'Effet Fleur", description: "flower shop in tain-l'hermitage.", tags: ["shop","art"] },
  { id: "lamaisondesfondues", label: "La Maison des Fondues", description: "fondue restaurant in aix-en-provence.", tags: ["food"] },
  { id: "lamidupain", label: "L'Ami du Pain", description: "bakery in calas.", tags: ["food"] },
  { id: "lapetiteferme", label: "La Petite Ferme", description: "amazing semi-gourmet restaurant in aix-en-provence. same card as côté cour, a gourmet restaurant by the same chef.", tags: ["food"] },
  { id: "laplace", label: "La Place", description: "pub in puyloubier.", tags: ["food"] },
  { id: "latelierburger", label: "L'Atelier Burger", description: "burger restaurant in bouc-bel-air, now closed.", tags: ["food"] },
  { id: "laterrassebiaggi", label: "La Terrasse Biaggi", description: "a rooftop in marseille, i think i went there on my first day of fourth year of cs.", tags: ["food"] },
  { id: "lebelange", label: "Le Bel'Ange", description: "barbershop in aix-en-provence.", tags: ["wellness", "shop"] },
  { id: "lecesar", label: "Le Cesar", description: "seafood (mostly) restaurant in sausset-les-pins.", tags: ["food"] },
  { id: "lelocal", label: "Le Local", description: "very good corsican restaurant in bouc-bel-air.", tags: ["food"] },
  { id: "lequai", label: "Le Quai", description: "restaurant in sausset-les-pins.", tags: ["food"] },
  { id: "lesbainsdulotus", label: "Les Bains du Lotus", description: "great hammam/spa in marrakech, loved it.", tags: ["wellness"] },
  { id: "lesfilsamaman", label: "Les Fils a Maman", description: "french restaurant in aix-en-provence.", tags: ["food"] },
  { id: "lesparfumsdegrasse", label: "Les Parfums de Grasse", description: "local perfume shop in fontaine-de-vaucluse, from which i buy my perfume online every year now.", tags: ["wellness", "shop"] },
  { id: "lesterrasses", label: "Les Terrasses", description: "seafood restaurant in carry-le-rouet.", tags: ["food"] },
  { id: "letainois", label: "Le Tainois", description: "a pub i may have gone to during a business seminar in tournon, i'm not sure i remember this one well.", tags: ["food"] },
  { id: "londonsubwayticket", label: "London Subway Ticket", description: "london subway ticket to south kensington, bought during my vacation there with my girlfriend <3.", tags: ["transport"] },
  { id: "lepotitatelier", label: "Le Pôtitatelier", description: "wonderful pottery based on sea creatures i came across at a pottery market in cabriès.", tags: ["craftsmanship", "art"] },
  { id: "lepetitbistro", label: "Le Petit Bistrot", description: "pub/restaurant in aix-en-provence.", tags: ["food"] },
  { id: "manae", label: "Manae", description: "jewelry shop in marseille.", tags: ["fashion", "shop"] },
  { id: "maisonbremond1830", label: "Maison Bremond 1830", description: "provencal gourmet food store.", tags: ["food", "shop"] },
  { id: "maisonjeandittalon", label: "Maison Jean Dit Talon", description: "bakery in arles.", tags: ["food"] },
  { id: "maisonmooks", label: "Maison Mooks", description: "japanese pastry shop in aix-en-provence ", tags: ["food"] },
  { id: "mamanelly", label: "Mama Nelly", description: "african restaurant in marseille.", tags: ["food"] },
  { id: "marrakechmuseum", label: "Marrakech Museum", description: "ticket to the marrakech museum, in marrakech, by the omar benjelloun foundation.", tags: ["art"] },
  { id: "martharotten", label: "Martha Rotten", description: "very cool online alt/goth hand-made jewelry brand.", tags: ["craftsmanship","fashion"] },
  { id: "meowcatscafe", label: "Meow Cats Cafe", description: "cat cafe in aix-en-provence, very cute cats.", tags: ["food","wellness"] },
  { id: "musiquenumero1", label: "Musique N°1", description: "music shop, selling instruments and other stuff, in plan-de-campagne.", tags: ["art", "shop"] },
  { id: "mo-mo", label: "Mö-Mö", description: "good restaurant in marrakech.", tags: ["food"] },
  { id: "myjewelledbox", label: "My Jewelled Box", description: "very beautiful and creative artisanal jewelry, seen at the royal mile market in edinburgh.", tags: ["craftsmanship", "fashion", "shop"] },
  { id: "naruto", label: "Naruto", description: "very good japanese restaurant in aix-en-provence. the boss is really nice and makes funny reels on instagram.", tags: ["food"] },
  { id: "newrock", label: "New Rock", description: "card that came in the package of my very cool new rock boots.", tags: ["fashion"] },
  { id: "nino", label: "Nino", description: "italian restaurant in plan-de-campagne.", tags: ["food"] },
  { id: "noxkensington", label: "Nox Kensington", description: "kensington nox hotel, in london.", tags: ["wellness"] },
  { id: "operecuisinedamour", label: "Opère Cuisine d'Amour", description: "good restaurant around aix-en-provence.", tags: ["food"] },
  { id: "petrarque&laure", label: "Pétrarque & Laure", description: "restaurant in fontaine-de-vaucluse.", tags: ["food"] },
  { id: "pizzalaboucaine", label: "Pizza la Boucaine", description: "pizza truck in bouc-bel-air.", tags: ["food"] },
  { id: "primapasta", label: "Prima Pasta", description: "italian pasta restaurant in aix-en-provence.", tags: ["food"] },
  { id: "puysaintvincent", label: "Puy-Saint-Vincent", description: "chair lift access card to use in the Puy-Saint-Vincent ski station.", tags: ["transport"] },
  { id: "retrosatanas", label: "Retro Satanas", description: "cool online alt clothing brand.", tags: ["fashion"] },
  { id: "robertofanti", label: "Roberto Fanti", description: "my hairdresser for the past few years, in aix-en-provence.", tags: ["wellness"] },
  { id: "sandrineberthon", label: "Sandrine Berthon", description: "sandrine berthon, french visual artist. seen in gordes.", tags: ["art"] },
  { id: "sebastienallart", label: "Sébastien Allart", description: "my favorite modern painter, located in aix-en-provence. i've been a fan of his work since i was a child.", tags: ["art"] },
  { id: "seito", label: "Seito", description: "korean bbq restaurant in aix-en-provence.", tags: ["food"] },
  { id: "tabio", label: "Tabio", description: "socks and tabi shoes brand.", tags: ["fashion"] },
  { id: "thewitchery", label: "The Witchery", description: "very cool and classy witchcraft shop in edinburgh.", tags: ["shop"] },
  { id: "uplandsroast", label: "Uplands Roast", description: "small cafe in edinburgh, they make the best hot chocolate i ever tried, with toasted marshmallows, cinnamon, etc.", tags: ["food"] },
  { id: "viviennewestwood", label: "Vivienne Westwood", description: "found in the bag of my vivienne westwood armor ring, which i bought in london.", tags: ["fashion", "shop"] },
  { id: "wittchen", label: "Wittchen", description: "piece of cardboard found in my wittchen wallet i got for my birthday.", tags: ["fashion"] },
  { id: "youfoundmeskullpanda", label: "You Found Me ! SKULLPANDA", description: "card that comes in skullpanda collection boxes.", tags: ["miscellaneous"] },
  { id: "yojisu", label: "Yojisu", description: "japanese restaurant around aix-en-provence.", tags: ["food"] },
    // { id: "cards", label: "card", description: "Q izgeg dolor zgeg", tags: ["miscellaneous"] },
];

export const cardList: CardData[] = CARD_DEFINITIONS.map(({ id, label, description, tags }) => ({
  id,
  label,
  description,
  front: `/assets/cards/${id}_r.png`,
  back: `/assets/cards/${id}_v.png`,
  tags,
}));
